const students = [
    {
      id: 1,
      nombre: "Carlos",
      apellido: "Hernández",
      nombre_usuario: "carlos_h",
      contraseña: "carlos123",
      color_tema: "#1A73E8",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-09-01",
      foto_perfil: "https://randomuser.me/api/portraits/men/1.jpg"
    },
    {
      id: 2,
      nombre: "María",
      apellido: "González",
      nombre_usuario: "maria_g",
      contraseña: "maria456",
      color_tema: "#FF5733",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-08-15",
      foto_perfil: "https://randomuser.me/api/portraits/women/2.jpg"
    },
    {
      id: 3,
      nombre: "Luis",
      apellido: "Martínez",
      nombre_usuario: "luis_m",
      contraseña: "luis789",
      color_tema: "#FFC107",
      tamaño_letra: "16px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-09-10",
      foto_perfil: "https://randomuser.me/api/portraits/men/3.jpg"
    },
    {
      id: 4,
      nombre: "Ana",
      apellido: "López",
      nombre_usuario: "ana_l",
      contraseña: "ana001",
      color_tema: "#00BFA5",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-10-01",
      foto_perfil: "https://randomuser.me/api/portraits/women/4.jpg"
    },
    {
      id: 5,
      nombre: "Miguel",
      apellido: "Pérez",
      nombre_usuario: "miguel_p",
      contraseña: "miguel002",
      color_tema: "#9C27B0",
      tamaño_letra: "13px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-07-20",
      foto_perfil: "https://randomuser.me/api/portraits/men/5.jpg"
    },
    {
      id: 6,
      nombre: "Lucía",
      apellido: "Díaz",
      nombre_usuario: "lucia_d",
      contraseña: "lucia003",
      color_tema: "#03A9F4",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-08-30",
      foto_perfil: "https://randomuser.me/api/portraits/women/6.jpg"
    },
    {
      id: 7,
      nombre: "Daniel",
      apellido: "Fernández",
      nombre_usuario: "daniel_f",
      contraseña: "daniel004",
      color_tema: "#E91E63",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-09-25",
      foto_perfil: "https://randomuser.me/api/portraits/men/7.jpg"
    },
    {
      id: 8,
      nombre: "Laura",
      apellido: "Jiménez",
      nombre_usuario: "laura_j",
      contraseña: "laura005",
      color_tema: "#8BC34A",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-10-15",
      foto_perfil: "https://randomuser.me/api/portraits/women/8.jpg"
    },
    {
      id: 9,
      nombre: "David",
      apellido: "Ruiz",
      nombre_usuario: "david_r",
      contraseña: "david006",
      color_tema: "#FF9800",
      tamaño_letra: "13px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-07-05",
      foto_perfil: "https://randomuser.me/api/portraits/men/9.jpg"
    },
    {
      id: 10,
      nombre: "Sara",
      apellido: "Sánchez",
      nombre_usuario: "sara_s",
      contraseña: "sara007",
      color_tema: "#CDDC39",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 1,
      fecha_inicio: "2024-08-22",
      foto_perfil: "https://randomuser.me/api/portraits/women/10.jpg"
    },
    {
      id: 11,
      nombre: "Fernando",
      apellido: "Castro",
      nombre_usuario: "fernando_c",
      contraseña: "fernando008",
      color_tema: "#F44336",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-09-12",
      foto_perfil: "https://randomuser.me/api/portraits/men/11.jpg"
    },
    {
      id: 12,
      nombre: "Elena",
      apellido: "Martínez",
      nombre_usuario: "elena_m",
      contraseña: "elena009",
      color_tema: "#9C27B0",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-08-20",
      foto_perfil: "https://randomuser.me/api/portraits/women/12.jpg"
    },
    {
      id: 13,
      nombre: "Ricardo",
      apellido: "Vega",
      nombre_usuario: "ricardo_v",
      contraseña: "ricardo010",
      color_tema: "#FFEB3B",
      tamaño_letra: "16px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-08-18",
      foto_perfil: "https://randomuser.me/api/portraits/men/13.jpg"
    },
    {
      id: 14,
      nombre: "Isabel",
      apellido: "García",
      nombre_usuario: "isabel_g",
      contraseña: "isabel011",
      color_tema: "#8BC34A",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-09-02",
      foto_perfil: "https://randomuser.me/api/portraits/women/14.jpg"
    },
    {
      id: 15,
      nombre: "José",
      apellido: "Ramírez",
      nombre_usuario: "jose_r",
      contraseña: "jose012",
      color_tema: "#03A9F4",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 1,
      fecha_inicio: "2024-08-10",
      foto_perfil: "https://randomuser.me/api/portraits/men/15.jpg"
    },
    {
      id: 16,
      nombre: "Patricia",
      apellido: "López",
      nombre_usuario: "patricia_l",
      contraseña: "patricia013",
      color_tema: "#FF5722",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-09-05",
      foto_perfil: "https://randomuser.me/api/portraits/women/16.jpg"
    },
    {
      id: 17,
      nombre: "Javier",
      apellido: "Mora",
      nombre_usuario: "javier_m",
      contraseña: "javier014",
      color_tema: "#9C27B0",
      tamaño_letra: "13px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-08-17",
      foto_perfil: "https://randomuser.me/api/portraits/men/17.jpg"
    },
    {
      id: 18,
      nombre: "Raquel",
      apellido: "Pérez",
      nombre_usuario: "raquel_p",
      contraseña: "raquel015",
      color_tema: "#FF9800",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-09-19",
      foto_perfil: "https://randomuser.me/api/portraits/women/18.jpg"
    },
    {
      id: 19,
      nombre: "Carlos",
      apellido: "Gutiérrez",
      nombre_usuario: "carlos_g",
      contraseña: "carlos016",
      color_tema: "#CDDC39",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-08-25",
      foto_perfil: "https://randomuser.me/api/portraits/men/19.jpg"
    },
    {
      id: 20,
      nombre: "Marta",
      apellido: "Sánchez",
      nombre_usuario: "marta_s",
      contraseña: "marta017",
      color_tema: "#8BC34A",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 1,
      fecha_inicio: "2024-07-22",
      foto_perfil: "https://randomuser.me/api/portraits/women/20.jpg"
    },
    {
      id: 21,
      nombre: "Antonio",
      apellido: "González",
      nombre_usuario: "antonio_g",
      contraseña: "antonio018",
      color_tema: "#1A73E8",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-07-29",
      foto_perfil: "https://randomuser.me/api/portraits/men/21.jpg"
    },
    {
      id: 22,
      nombre: "Clara",
      apellido: "Jiménez",
      nombre_usuario: "clara_j",
      contraseña: "clara019",
      color_tema: "#FF5733",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-09-13",
      foto_perfil: "https://randomuser.me/api/portraits/women/22.jpg"
    },
    {
      id: 23,
      nombre: "Fernando",
      apellido: "Hernández",
      nombre_usuario: "fernando_h",
      contraseña: "fernando020",
      color_tema: "#FFC107",
      tamaño_letra: "16px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-09-11",
      foto_perfil: "https://randomuser.me/api/portraits/men/23.jpg"
    },
    {
      id: 24,
      nombre: "Sofía",
      apellido: "Rodríguez",
      nombre_usuario: "sofia_r",
      contraseña: "sofia021",
      color_tema: "#00BFA5",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-09-22",
      foto_perfil: "https://randomuser.me/api/portraits/women/24.jpg"
    },
    {
      id: 25,
      nombre: "Ricardo",
      apellido: "Vega",
      nombre_usuario: "ricardo_v",
      contraseña: "ricardo022",
      color_tema: "#9C27B0",
      tamaño_letra: "13px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-08-19",
      foto_perfil: "https://randomuser.me/api/portraits/men/25.jpg"
    },
    {
      id: 26,
      nombre: "Natalia",
      apellido: "Mendoza",
      nombre_usuario: "natalia_m",
      contraseña: "natalia023",
      color_tema: "#03A9F4",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 1,
      fecha_inicio: "2024-09-14",
      foto_perfil: "https://randomuser.me/api/portraits/women/26.jpg"
    },
    {
      id: 27,
      nombre: "Emilio",
      apellido: "Sánchez",
      nombre_usuario: "emilio_s",
      contraseña: "emilio024",
      color_tema: "#E91E63",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-07-10",
      foto_perfil: "https://randomuser.me/api/portraits/men/27.jpg"
    },
    {
      id: 28,
      nombre: "Carmen",
      apellido: "Martín",
      nombre_usuario: "carmen_m",
      contraseña: "carmen025",
      color_tema: "#FF9800",
      tamaño_letra: "13px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-08-24",
      foto_perfil: "https://randomuser.me/api/portraits/women/28.jpg"
    },
    {
      id: 29,
      nombre: "Andrés",
      apellido: "Gutiérrez",
      nombre_usuario: "andres_g",
      contraseña: "andres026",
      color_tema: "#CDDC39",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-09-16",
      foto_perfil: "https://randomuser.me/api/portraits/men/29.jpg"
    },
    {
      id: 30,
      nombre: "Verónica",
      apellido: "Fernández",
      nombre_usuario: "veronica_f",
      contraseña: "veronica027",
      color_tema: "#8BC34A",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-09-08",
      foto_perfil: "https://randomuser.me/api/portraits/women/30.jpg"
    },
    {
      id: 31,
      nombre: "Santiago",
      apellido: "Ramírez",
      nombre_usuario: "santiago_r",
      contraseña: "santiago028",
      color_tema: "#F44336",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 1,
      fecha_inicio: "2024-07-28",
      foto_perfil: "https://randomuser.me/api/portraits/men/31.jpg"
    },
    {
      id: 32,
      nombre: "Gabriela",
      apellido: "Álvarez",
      nombre_usuario: "gabriela_a",
      contraseña: "gabriela029",
      color_tema: "#FF5733",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-08-05",
      foto_perfil: "https://randomuser.me/api/portraits/women/32.jpg"
    },
    {
      id: 33,
      nombre: "Felipe",
      apellido: "Ruiz",
      nombre_usuario: "felipe_r",
      contraseña: "felipe030",
      color_tema: "#FFC107",
      tamaño_letra: "16px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-08-12",
      foto_perfil: "https://randomuser.me/api/portraits/men/33.jpg"
    },
    {
      id: 34,
      nombre: "Olga",
      apellido: "Córdoba",
      nombre_usuario: "olga_c",
      contraseña: "olga031",
      color_tema: "#00BFA5",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-07-17",
      foto_perfil: "https://randomuser.me/api/portraits/women/34.jpg"
    },
    {
      id: 35,
      nombre: "Joaquín",
      apellido: "Vázquez",
      nombre_usuario: "joaquin_v",
      contraseña: "joaquin032",
      color_tema: "#9C27B0",
      tamaño_letra: "13px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-07-24",
      foto_perfil: "https://randomuser.me/api/portraits/men/35.jpg"
    },
    {
      id: 36,
      nombre: "Mónica",
      apellido: "García",
      nombre_usuario: "monica_g",
      contraseña: "monica033",
      color_tema: "#03A9F4",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 1,
      fecha_inicio: "2024-09-01",
      foto_perfil: "https://randomuser.me/api/portraits/women/36.jpg"
    },
    {
      id: 37,
      nombre: "Manuel",
      apellido: "López",
      nombre_usuario: "manuel_l",
      contraseña: "manuel034",
      color_tema: "#E91E63",
      tamaño_letra: "12px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-08-14",
      foto_perfil: "https://randomuser.me/api/portraits/men/37.jpg"
    },
    {
      id: 38,
      nombre: "Leticia",
      apellido: "Ramírez",
      nombre_usuario: "leticia_r",
      contraseña: "leticia035",
      color_tema: "#FF9800",
      tamaño_letra: "13px",
      tipo_usuario: "estudiante",
      supervisado_por: 2,
      fecha_inicio: "2024-07-30",
      foto_perfil: "https://randomuser.me/api/portraits/women/38.jpg"
    },
    {
      id: 39,
      nombre: "Álvaro",
      apellido: "Pérez",
      nombre_usuario: "alvaro_p",
      contraseña: "alvaro036",
      color_tema: "#CDDC39",
      tamaño_letra: "15px",
      tipo_usuario: "estudiante",
      supervisado_por: 4,
      fecha_inicio: "2024-08-03",
      foto_perfil: "https://randomuser.me/api/portraits/men/39.jpg"
    },
    {
      id: 40,
      nombre: "Patricia",
      apellido: "González",
      nombre_usuario: "patricia_g",
      contraseña: "patricia037",
      color_tema: "#8BC34A",
      tamaño_letra: "14px",
      tipo_usuario: "estudiante",
      supervisado_por: 3,
      fecha_inicio: "2024-09-20",
      foto_perfil: "https://randomuser.me/api/portraits/women/40.jpg"
    }
  ];

  export function getEstudiantes(condicion) {
    return condicion ? students : [];
  };
  