version: '3'

services:
  db:
    image: mysql:latest  # o puedes usar mariadb:latest si prefieres MariaDB
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Contraseña de root
      MYSQL_DATABASE: dgp  # Base de datos predeterminada
      MYSQL_USER: user  # Usuario para la base de datos
      MYSQL_PASSWORD: password  # Contraseña para el usuario
    ports:
      - "3307:3306"  # Exponer el puerto 3306 para MySQL
    volumes:
      - db_data:/var/lib/mysql  # Volumen persistente para los datos

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  # Nombre del contenedor de MySQL
      PMA_USER: root  # Usuario root
      PMA_PASSWORD: rootpassword  # Contraseña root
    ports:
      - "8080:80"  # Exponer phpMyAdmin en el puerto 8080

volumes:
  db_data:
